### ISSUE TITLE
PHP Fatal Error

### ISSUE THREAD

**Issue by logonarium** [vgrish/userfiles#1]
На чистой свежеустановленной modx 2.5.1 установка UserFiles вызывает Fatal Error при попытке зайти на страницу редактирования пользователя в админке

Fatal error: Call to a member function get() on array in /.../manager/controllers/default/security/user/update.class.php on line 108

Проверялось на версиях UserFiles 2.1.16, 2.1.17 и 2.2.0
Как только сносишь компонент — все работает как надо.

**Comment by vgrish** [comment]
- fix https://github.com/vgrish/userfiles/commit/f808c0b2008c3e4ff5201383bd8e4814136ed3e6
